export enum TransferStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethodType {
  CARD = 'CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  MOBILE_MONEY = 'MOBILE_MONEY',
  CRYPTO = 'CRYPTO',
}

export enum TransactionType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
  FEE = 'FEE',
  REFUND = 'REFUND',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  SUCCESS = 'SUCCESS', // Added missing SUCCESS status
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  TRANSFER_SENT = 'TRANSFER_SENT',
  TRANSFER_RECEIVED = 'TRANSFER_RECEIVED',
  TRANSFER_COMPLETED = 'TRANSFER_COMPLETED',
  TRANSFER_FAILED = 'TRANSFER_FAILED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  SECURITY_ALERT = 'SECURITY_ALERT',
  PAYMENT_METHOD_ADDED = 'PAYMENT_METHOD_ADDED', // Added missing notification type
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED', // Added missing notification type
}

export enum OTPType {
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
}

export enum FeeType {
  TRANSFER_FEE = 'TRANSFER_FEE',
  CURRENCY_CONVERSION_FEE = 'CURRENCY_CONVERSION_FEE',
  WITHDRAWAL_FEE = 'WITHDRAWAL_FEE',
  CARD_PROCESSING_FEE = 'CARD_PROCESSING_FEE',
}